name: Build and Deploy with Kaniko

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    outputs:
      s3_uri: ${{ steps.upload.outputs.S3_URI }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update

    - name: Upload repository to S3
      id: upload
      run: |
        set -e
        # Variables
        LOCAL_DIR="${{ github.workspace }}"
        S3_BUCKET="${{ secrets.S3_BUCKET }}"
        S3_KEY="artifacts"

        tar -C ${{ github.workspace }} -zcvf context.tar.gz .

        # Upload to S3
        aws s3 cp context.tar.gz s3://${{ secrets.S3_BUCKET }}/$S3_KEY/context.tar.gz --region us-east-1

        # Get the S3 URI
        S3_URI="s3://$S3_BUCKET/$S3_KEY"

        # Output the S3 URI for the next step
        echo "S3_URI=$S3_URI" >> $GITHUB_OUTPUT

    - name: Run ECS task with overrides
      run: |
        set -e

        # Load the S3 URI
        echo "${{ steps.upload.outputs.S3_URI }}"
        S3_URI=${{ steps.upload.outputs.S3_URI }}

        # Variables
        CLUSTER_NAME="${{ secrets.CLUSTER_NAME }}"
        SUBNETS="${{ secrets.SUBNETS }}"  # Comma-separated list of subnet IDs
        SECURITY_GROUPS="${{ secrets.SECURITY_GROUPS }}"  # Comma-separated list of security group IDs
        TASK_FAMILY="kaniko-demo"
        TASK_DEFINITION="${{ secrets.TASK_DEFINITION }}"  # The ARN or family name of the task definition to use
        KANIKO_DEMO_IMAGE="${{ secrets.KANIKO_DEMO_IMAGE }}"
        AWS_REGION="${{ secrets.AWS_REGION }}"

        # Run the ECS task with command override
        aws ecs run-task \
            --cluster $CLUSTER_NAME \
            --task-definition $TASK_DEFINITION \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={subnets=[$SUBNETS],securityGroups=[$SECURITY_GROUPS],assignPublicIp=ENABLED}" \
            --region us-east-1 \
            --overrides '{
                "containerOverrides": [
                    {
                        "name": "kaniko",
                        "command": [
                            "--context", "'"$S3_URI/context.tar.gz"'",
                            "--dockerfile", "Dockerfile",
                            "--destination", "'"$KANIKO_DEMO_IMAGE"'",
                            "--force"
                        ]
                    }
                ]
            }'